version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "uv"
    directory: "notebooks"
    schedule:
      interval: "weekly"
  - package-ecosystem: "opentofu"
    directory: "deploy/tf/"
    schedule:
      interval: "weekly"
